---
kind: pipeline
name: testing

clone:

steps:
  - name: download
    image: joomlaprojects/docker-images:packager
    commands:
      - cd packages
      - wget https://developer.joomla.org/nightlies/Joomla_4.3.0-dev-Development-Full_Package.zip
      - wget https://developer.joomla.org/nightlies/Joomla_5.0.0-dev-Development-Full_Package.zip

  - name: extract
    image: joomlaprojects/docker-images:packager
    depends_on: [ download ]
    commands:
      - rm -rf install/4.3.0
      - unzip packages/Joomla_4.3.0-dev-Development-Full_Package.zip -d install/4.3.0

  - name: npm
    image: node:16-bullseye-slim
    depends_on: [ extract ]
    commands:
      - npm ci --unsafe-perm

  - name: prepare_system_tests
    depends_on:
      - npm
    image: joomlaprojects/docker-images:systemtests
    volumes:
      - name: cypress-cache
        path: /root/.cache/Cypress
    commands:
      - npx cypress install
      - npx cypress verify

  - name: mysqlhealthcheck
    image: mysql:5.7
    depends_on: [ npm ]
    commands:
      - while ! mysqladmin ping -h mysql -u joomla_ut -pjoomla_ut --silent; do sleep 1; done

  - name: test-dpcalendar
    image: joomlaprojects/docker-images:cypress
    depends_on: [ npm ]
    volumes:
      - name: cypress-cache
        path: /root/.cache/Cypress
    environment:
      JOOMLA_INSTALLATION_DISABLE_LOCALHOST_CHECK: 1
    commands:
      - php install/4.3.0/installation/joomla.php install --site-name=extension-test --admin-user=john --admin-username=john-ext --admin-password=lalalal123lalala --admin-email=john@example.com --db-type=mysqli --db-host=mysql --db-user=joomla_ut --db-pass=joomla_ut --db-name=test_joomla --db-prefix=et4_
      - cd /packages
      - wget -i extensions/dpcalendar/url.txt -O dpcalendar.zip
      - cd ..
      - php install/4.3.0/cli/joomla.php extension:install --path packages/dpcalendar.zip --verbose  --version --no-interaction
      - npx cypress run --record --config-file "cypress.config.js" --spec "extensions/dpcalendar/tests/default/Installed.cy.js"

volumes:
  - name: cypress-cache
    host:
      path: /tmp/cypress-cache

services:
  - name: mysql
    image: mysql:5.7
    environment:
      MYSQL_USER: joomla_ut
      MYSQL_PASSWORD: joomla_ut
      MYSQL_ROOT_PASSWORD: joomla_ut
      MYSQL_DATABASE: test_joomla
