---
kind: pipeline
name: testing

clone:

steps:
  - name: download
    image: joomlaprojects/docker-images:packager
    volumes:
      - name: packagedir
        path: /packagedir
    commands:
      - cd /packagedir
      - wget https://developer.joomla.org/nightlies/Joomla_4.3.0-dev-Development-Full_Package.zip
      - wget https://developer.joomla.org/nightlies/Joomla_5.0.0-dev-Development-Full_Package.zip

  - name: extract
    image: joomlaprojects/docker-images:packager
    depends_on: [ download ]
    volumes:
      - name: installdir
        path: /installdir
      - name: packagedir
        path: /packagedir
    commands:
      - rm -rf /installdir/4.3.0
      - unzip /packagedir/Joomla_4.3.0-dev-Development-Full_Package.zip -d /installdir/4.3.0

  - name: npm
    image: node:16-bullseye-slim
    depends_on: [ extract ]
    volumes:
      - name: npm-cache
        path: /tmp/npm-cache
    environment:
      npm_config_cache: /tmp/npm-cache
    commands:
      - npm ci --unsafe-perm

  - name: mysqlhealthcheck
    image: mysql:5.7
    depends_on: [ n ]
    commands:
      - while ! mysqladmin ping -h mysql -u joomla_ut -pjoomla_ut --silent; do sleep 1; done

  - name: test-dpcalendar
    image: joomlaprojects/docker-images:cypress
    depends_on: [ npm ]
    volumes:
      - name: installdir
        path: /installdir
      - name: packagedir
        path: /packagedir
    environment:
      JOOMLA_INSTALLATION_DISABLE_LOCALHOST_CHECK: 1
    commands:
      - php /installdir/4.3.0/installation/joomla.php install --site-name=extension-test --admin-user=john --admin-username=john-ext --admin-password=lalalal123lalala --admin-email=john@example.com --db-type=mysqli --db-host=mysql --db-user=joomla_ut --db-pass=joomla_ut --db-name=test_joomla --db-prefix=et4_
      - cd /packagedir
      - wget -i extensions/dpcalendar/url.txt -O dpcalendar.zip
      - cd ..
      - php /installdir/4.3.0/cli/joomla.php extension:install --path /packagedir/dpcalendar.zip --verbose  --version --no-interaction

volumes:
  - name: installdir
    host:
      path: /tmp/et-install-dir

  - name: packagedir
    host:
      path: /tmp/et-package-dir


services:
  - name: mysql
    image: mysql:5.7
    environment:
      MYSQL_USER: joomla_ut
      MYSQL_PASSWORD: joomla_ut
      MYSQL_ROOT_PASSWORD: joomla_ut
      MYSQL_DATABASE: test_joomla
